### ISSUE TITLE
Servo jumps to target position when multiple servo commands used

### ISSUE THREAD

**Issue by piersstorey** [piersstorey/mearm_micropython#1]
## Issue
When running multiple servo commands a servo will jump to the target position instead of smoothly moving from the existing position to the target position.  

### Espected behaviour  
When a single servo is given a command to move to a new position, the servo will use a Python range `range(start,end,step)` from the existing position to the target position and include a step to determine the number of position changes between the start and target position. This produces a smooth movement to the target position.  

### Reproduce expected behaviour  
```python
from mearm import MeArm
me_arm = MeArm()
me_arm.height.move_to(100)
me_arm.height.move_to(0)
```

### Defect behaviour  
If multiple servo positions are changed, a servo will move between the existing and target positions without iterating through the range steps.

### Reproduce defect behaviour  
```python
from mearm import MeArm
me_arm = MeArm()
me_arm.height.move_to(100)
me_arm.reach.move_to(60)
```

**Comment by carlosperate** [comment]
Hi Piers,

Just to confirm, with the first block of code, the `height` servo will move from its initial position to `100`, and then from `100` to `0`, so there are two movements with steps in the middle for both, is that right?

```python
from mearm import MeArm
me_arm = MeArm()
me_arm.height.move_to(100)
me_arm.height.move_to(0)
```


Then, for the second code block, the `height` servo will move from its initial position to `100` and the `reach` servo will move from its initial position to `60`, but they will move instantly, without any in-between steps, correct?
```python
from mearm import MeArm
me_arm = MeArm()
me_arm.height.move_to(100)
me_arm.reach.move_to(60)
```


What happens with this code block?
Are both movements (initial to `100`/`60` and then down to `0`) for both servos inmediate without any in-between steps?

```python
from mearm import MeArm
me_arm = MeArm()
me_arm.height.move_to(100)
me_arm.reach.move_to(60)
me_arm.height.move_to(0)
me_arm.reach.move_to(0)
```

**Comment by carlosperate** [comment]
Btw, are all servo instances overwritting the same settings file?
https://github.com/piersstorey/mearm_micropython/blob/main/mearm.py#L58
So, when each `Servo` instance is created, all instances load the same settings data from the `Servo.save_pos()` last executed?

**Comment by cssbz** [comment]
Hi. This sounded interesting. I don't have any servo hardware available, so I added some `print` statements, so I could see what was going on, and run the code without any attached hardware.

In `set_servo_cycle`, I added `print(self.servo, position)`.

In `save_pos`, I added `print("SAVE", servo, pos)`, and, after `self.settings[servo] = pos`, I added `print(self.settings)`.

I could then reproduce the problem.

I'm starting with settings.json containing `{"base": 5660, "reach": 6070, "height": 2520, "grip": 4330}`.

If I run the defect behaviour code, I see:

```
height 2520
height 2550
height 2580
height 2610
...
height 5880
height 5910
height 5940
height 5970
SAVE height 5970
{'base': 5660, 'reach': 6070, 'height': 5970, 'grip': 4330}
reach 6070
SAVE reach 6070
{'base': 5660, 'reach': 6070, 'height': 2520, 'grip': 4330}
```

The first line of `settings` output looks as I expected... the final value of `5970` for `height` has been recorded.

But notice that in the second line of `settings` output, the `height` has been changed back to the initial value of `2520`. This then causes the height servo to jump back to that position on the next run of the program.

I think this is happening because each of the four `Servo` objects has a *copy* of `settings`, containing the values for all four servos. So, above, the `Servo` instance for `height` writes the settings file, with the new value for `height`. Then, the `Servo` instance for `reach` becomes active, dealing with the requested change to the `reach` position. But the `Servo` instance for `reach` is unaware of the change to the `height` value. When it saves the settings file, it writes the original value for `height`.

I hope this makes sense. It's not a brilliant explanation. Please do say if I need to clarify anything.

I can imagine a few possible fixes, but I haven't tested any. A simple fix would be to read the current contents of the settings file before setting a new value and writing it out again. Alternatives could be to use a separate file for each servo, or to implement one central settings dictionary variable... perhaps make it a variable within the `MeArm` class rather than `Servo`?

EDIT: oops, didn't realise I was writing at the same time as carlosperate until I hit Submit - apologies.

**Comment by piersstorey** [comment]
Thanks @carlosperate, @cssbz, your comments helped to resolve the issue. The code is a little more verbose and can be improved/optimized but the bug has now been resolved.
